### ISSUE TITLE
RuntimeError: Failed to parse Dictionary from the input stream

### ISSUE THREAD

**Issue by pamio** [CatalystCode/VoTT#141]
Hi, I have a trained model that sort of works fine but I want to improve its accuracy by retraining on new images through VoTT. 

Here is what I tried. 

- Downloaded the app and ran VoTT.exe 

- Open a directory of images and added tags in the textfield.

-  Tag few images and export them

- Ctrl+R to add model path - I have a trained model in c:\p\model\frcnn_svm.model along with a file name model.json with all the tags in it. 

- Click on review and bang! This is what I get from the developer console 

                  Error: CNTK Process failed with error code 1
                 Error output:Traceback (most recent call last):
                  File "C:\VoTT\resources\app\node_modules\cntk-fastrcnn\src\frcnn_detector.py", line 364, in <module>
                 detector.load_model()
                  File "C:\VoTT\resources\app\node_modules\cntk-fastrcnn\src\frcnn_detector.py", line 111, in   load_model
                   trained_frcnn_model = load_model(self.__model_path)
                  File "c:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-   packages\cntk\internal\swig_helper.py", line 69, in wrapper
                   result = f(*args, **kwds)
                   File "c:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\ops\functions.py", line 1599, in load_model
                   return Function.load(model, device)
                   File "c:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\internal\swig_helper.py", line 69, in wrapper
                   result = f(*args, **kwds)
                    File "c:\local\Anaconda3-4.1.1-Windows-x86_64\envs\cntk-py35\lib\site-packages\cntk\ops\functions.py", line 1513, in load
                   return cntk_py.Function.load(model, device)
                RuntimeError: Failed to parse Dictionary from the input stream.

         [CALL STACK]
              > CNTK::operator>>  
              - CNTK::Function::  Load
              - PyInit__cntk_py (x2)
             - PyCFunction_Call
             - PyEval_GetFuncDesc
             - PyEval_EvalFrameEx (x2)
             - PyFunction_SetAnnotations
             - PyObject_Call
             - PyEval_GetFuncDesc
             - PyEval_EvalFrameEx (x2)
             - PyEval_GetFuncDesc (x2)
             - PyEval_EvalFrameEx

              Selected GPU[0] Tesla K80 as the process wide default device.

                at ChildProcess.proc.on (C:\VoTT\resources\app\node_modules\cntk-fastrcnn\src\python_eval_client.js:82)
                 at emitTwo (events.js:106)
                 at ChildProcess.emit (events.js:191)
                at Process.ChildProcess._handle.onexit (internal/child_process.js:215)
                 C:\VoTT\resources\app\src\lib\detection_algorithms\cntkfastrcnn\reviewer.js:65 undefined
                 internal/process/next_tick.js:103 Uncaught (in promise) undefined
                _tickCallback @ internal/process/next_tick.js:103

Also I don't find a file named CNTK-Config.json under resources/app folder to specify the CNTK path. So I created a new file with the same name and added my CNTK path but it didn't pick. So I finally had top copy the CNTK folder in `local`. 

Can you help me with the issue ?

**Comment by aribornstein** [comment]
VoTT Currently doesn't support SVM for evaluation since the requires extra pipelining I recommend Iterating without the SVM component and adding it back in when you go to production since the goal of the SVM component is speed performance. Always open to a pull request on that issue

**Comment by pamio** [comment]
I did try to load `c:\p\model\frcnn_nn.model`, one without SVM but I still get the same error. Any ideas ?

**Comment by pamio** [comment]
My bad! I had refresh the app. Its working now. 
One more question: 
  How do I retain after exporting the tags ?
  Should I place this exported tags and images in the existing positive and testImages directory ? Or I only retrain only on the exported tags by computing ROIs ?

**Comment by aribornstein** [comment]
Glad that helped. To retrain you should merge the directories.

Best of luck,
-Ari
